### ISSUE TITLE
Run crawler standalone

### ISSUE THREAD

**Issue by ewul** [codelibs/fess-crawler#43]
Fess is good at search my files. Love it.
But actually, my files are in the other server.
So for now I have to transport these files to Fess server to crawl. (There's NO SMB...)

Can crawler running standalone beside fess to crawl file system?

**Comment by marevol** [comment]
A crawler of Fess is a just Java command.
You can check the command and args in debug logs of fess.log,
but I think a simple solution is to install Fess to the file server and connect it to elasticsearch in your server.
So, it's:
- Fess Server: Fess and Elasticsearch run
- File Server: only Fess runs and connects the above elasticsearch

**Comment by ewul** [comment]
Thank you.
I found command info in log.
