### ISSUE TITLE
Override crawling depth at Job Sheduler

### ISSUE THREAD

**Issue by chizenjp** [codelibs/fess-crawler#49]
On many URLs crawling takes long time.
Target site's top page will change while default crawling.

I have some idea to override crawl depth on Crawler settings Script column.
Like this

>return container.getComponent("crawlJob").logLevel("error").jobExecutor(executor).documentExpires(30).**depth(1)**.execute();

I'll use multiple default crawler has other depth.

Thanx

**Comment by marevol** [comment]
For issues other than bugs, please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
