### ISSUE TITLE
is it possible to crawl OAuth2 authenticated sites?

### ISSUE THREAD

**Issue by rajaseg** [codelibs/fess-crawler#61]
I want to crawl the Microsoft Stream Site ([Microsoft Stream](https://web.microsoftstream.com/studio/videos)) using fess-crawler. I think the site is protected with Oauth2.

Please let me know the steps.

**Comment by marevol** [comment]
It's not supported.

**Comment by rajaseg** [comment]
> It's not supported.

Can you help me to build a custom connector for the purpose?
